format = """
$kubernetes ❯❯ \
$directory \
$git_branch$git_commit$git_state$git_status\
($rust$nodejs)
$character 
"""

[directory]
format = "[$path]($style)[$lock_symbol]($lock_style)"
truncation_length = 10
truncate_to_repo = false

# TODO: see if the need for kubernetes context can be inferred
# from a working directory
[kubernetes]
disabled = false
format = "[$context(\\($namespace\\))]($style)"
style = "bold blue"

[git_branch]
style = "green"

[nodejs]
format = "[$symbol $version]($style) "

[rust]
format = "[$symbol$version]($style) "
